// Write a C# program to allow a user to guess a number( from 1 to 6) that will be
// randomly generated by computer. If guess is correct, display “You won”. Otherwise
// display “You lose”.



using System;

namespace HelloWorldApplication
{

    public class q9
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Guess the number");
            Int64 number = Convert.ToInt64(Console.ReadLine());
               Random rnd = new Random();
            //    Int64 min = 1;
            //    Int64 max = 6;

               Int64 randomNumber = rnd.Next(0,7);
               Console.WriteLine($"The number is {randomNumber}");

               if(number == randomNumber){
                    Console.WriteLine("You guessed Correctly !!");
               }else{
                    Console.WriteLine("Wrong !! Please try again");
               }

               

            Console.ReadKey();
        }
    }
}